# Learning Numpy & Pandas for Data Analysis
    Structure => Numpy multidimesnsional array
    Super Fast processing
    Deals only Numerical values
    

# Creating a Numpy Array

# 1- Dimensional array

In [13]:
# Importing Numpy (Numerical Python) Module 
import numpy as np

In [14]:
# using Python List
lst = [1,2,3,4,5,6,7,8,9,10]
print(type(lst))
arr1d = np.array(lst)

<class 'list'>


In [15]:
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
type(arr1d)

numpy.ndarray

In [17]:
arr1d[0]

1

In [18]:
arr1d[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr1d.max()

10

In [20]:
arr1d.min()

1

In [22]:
arr1d.sum()

55

In [28]:
arr1d.all()

True

In [31]:
lst = [1,2,3,4,5,6,7,8,9,10]
double= []
for a in lst:
    double.append(a*2)
double

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

# Vectorized Operation

In [32]:
arr1d*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [33]:
arr1d/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [37]:
arr1d.size

10

In [38]:
arr1d.ndim

1

In [39]:
arr1d.shape

(10,)

In [43]:
# Array Creation using Numpy arange 
arr1d = np.arange(12)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# 2D Array

In [51]:
# array using List
lst2d=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
lst2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [52]:
arr2d = np.array(lst2d)

In [53]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
arr2d.shape

(4, 3)

In [55]:
arr2d.ndim

2

In [56]:
arr2d+arr2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [57]:
arr2d*arr2d

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [60]:
arr3d = np.arange(36).reshape(6,6)
arr3d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [61]:
arr3d.ndim

2

In [62]:
arr3d.shape

(6, 6)

In [79]:
arr4d=arr3d.reshape(9,4)
arr4d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [66]:
arr4d.ndim

2

In [67]:
arr4d.shape

(9, 4)

In [68]:
arr5d=arr3d.reshape(10,4)
arr5d

ValueError: cannot reshape array of size 36 into shape (10,4)

In [73]:
lst2d=[[1,2,3],[4,5,6],[7,8,9,29],[10,11,12]]
arr5d=np.array(lst2d)
arr5d

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9, 29]),
       list([10, 11, 12])], dtype=object)

In [75]:
arr1d[5]

5

In [76]:
arr1d[4:5]

array([4])

In [81]:
#index value 23 from array
arr4d[5][3]

23

In [82]:
arr4d[5,3]

23

In [86]:
arr5d=arr3d.reshape(4,9)
arr5d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [88]:
# two portion while we slcicing of an array of 2d arr arr[row,col] => [startrow:endrow,startcoloumn:endcoloumn]
arr5d[1:2,2:7]

array([[11, 12, 13, 14, 15]])

In [95]:
arr5d[1:3,5:7]

array([[14, 15],
       [23, 24]])

In [97]:
arr5d[0:,6:]

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26],
       [33, 34, 35]])

In [98]:
# if we give all arguments of array in this array perform slicing [2:3,4:5] if any argument is missing then it return an index [:,2]
# return Index
arr5d[:,-1]

array([ 8, 17, 26, 35])

In [99]:
# Return slice
arr5d[0:,8:]

array([[ 8],
       [17],
       [26],
       [35]])

In [101]:
arr5d[:,[5,8,0,3]]

array([[ 5,  8,  0,  3],
       [14, 17,  9, 12],
       [23, 26, 18, 21],
       [32, 35, 27, 30]])

In [102]:
arr5d[[0,2],[2,7]]

array([ 2, 25])

In [103]:
arr5d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [104]:
arr5d[:,::2]

array([[ 0,  2,  4,  6,  8],
       [ 9, 11, 13, 15, 17],
       [18, 20, 22, 24, 26],
       [27, 29, 31, 33, 35]])

In [105]:
arr5d[:,::-2]

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [106]:
arr5d[::2,::2]

array([[ 0,  2,  4,  6,  8],
       [18, 20, 22, 24, 26]])

In [109]:
arr3d = np.arange(64).reshape(4,4,4) #(depth , row , coloumn)

In [108]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [114]:
arr3d[2,1,2]

38